<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Product_Search</name>
   <tag></tag>
   <elementGuidId>7b84cf22-ee26-4239-9392-152e8a274cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fixedPosition']/app-root/kendo-popup/div/div/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;fixedPosition&quot;)//following::span[@class=&quot;k-searchbox k-input k-input-md k-input-solid k-rounded-md&quot;]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.k-input-inner.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ccefe23c-52b0-4c79-81bf-5b76486ae28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5905da72-80f3-4cea-8fec-05f43782640c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>86e5840f-f6c5-4318-b627-ee72dacf76e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>9eee2fbf-75dd-497c-b3be-248f7cccd498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a8fefc5b-f9fb-41ed-abc9-ea4093cad821</value>
      <webElementGuid>38835309-e43c-4785-b9ed-a8b4efd0bd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>c6a0f09c-714c-4892-9b80-bb7d699455ec-</value>
      <webElementGuid>d827aa18-a7da-4487-8eae-9d1761bec5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixedPosition&quot;)//following::span[@class=&quot;k-searchbox k-input k-input-md k-input-solid k-rounded-md&quot;]/input</value>
      <webElementGuid>58909553-0ce3-4eeb-b205-fb0123302f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fixedPosition']/app-root/kendo-popup/div/div/span/input</value>
      <webElementGuid>23cd1748-cbc6-4047-a00a-6dd0e8243d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>c28930a3-ba43-4a4c-a25c-5cc271f6c795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
