<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parent_ActionLink_ParentRouteOperation</name>
   <tag></tag>
   <elementGuidId>f683ce44-504a-467b-8805-9127871d2017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tn_ProductRouteOperation&quot;)//following::a[@class=&quot;mat-menu-trigger gridAction ng-star-inserted&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.mat-menu-trigger.gridAction.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[3]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08654869-4abc-49a8-abad-4de19cc5a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c055778-62a9-421b-afb9-f67b5b55ea73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-menu-trigger gridAction ng-star-inserted</value>
      <webElementGuid>d6f3572f-4c55-46d2-a3b4-fddf9c393ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tn_ProductRouteOperation&quot;)//following::a[@class=&quot;mat-menu-trigger gridAction ng-star-inserted&quot;]</value>
      <webElementGuid>b5d5b4c3-a181-4546-8ff6-b7c0c343286c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[3]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td[2]/div/a</value>
      <webElementGuid>e89ff392-71ee-4862-b509-70317f09954d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lifecycle status'])[1]/following::a[3]</value>
      <webElementGuid>6eacaf94-f6e1-4312-b778-a0b43d6fd469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto release next operation'])[1]/following::a[4]</value>
      <webElementGuid>ce50342f-199a-495d-80f3-07edf29ba44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRO22000087'])[1]/preceding::a[2]</value>
      <webElementGuid>d6077ec2-a4fa-4fc5-a2c4-573a5e04dfcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProductRouteOperation Testing for Katalon PRO22000087'])[1]/preceding::a[2]</value>
      <webElementGuid>83c4adae-2249-403e-85e1-e1da5804d8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/a</value>
      <webElementGuid>38f00a00-e02e-4cf8-b75b-809365778194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
