<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parent_Link_AddProductRouteOperationWorkcenter</name>
   <tag></tag>
   <elementGuidId>46dcca14-a050-41f9-b9ea-0505a2fefb40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;cdk-overlay-0&quot;)//child::a[@class=&quot;dropdown-item ng-star-inserted&quot;][count(. | //*[(text() = 'Add product route operation workcenter' or . = 'Add product route operation workcenter')]) = count(//*[(text() = 'Add product route operation workcenter' or . = 'Add product route operation workcenter')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4b928d4-7b02-4251-b6a1-b2c244165865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item ng-star-inserted</value>
      <webElementGuid>75daebbc-01e9-4bfb-b22a-6a8f89b7fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add product route operation workcenter</value>
      <webElementGuid>7ac504e3-4616-4a2f-b89d-c4922ae8c0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)//child::a[@class=&quot;dropdown-item ng-star-inserted&quot;]</value>
      <webElementGuid>7ee9e03e-d1e6-409a-8930-968bee1fbf72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/div/div/div/a</value>
      <webElementGuid>2e9a566b-6d2a-445e-bd5e-d31f0c318d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add product route operation workcenter')]</value>
      <webElementGuid>23e86f72-5f13-4e20-95c1-584051a369be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::a[1]</value>
      <webElementGuid>9b35472c-6d37-466c-8dcb-ca28101b8598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::a[1]</value>
      <webElementGuid>3eccfbac-8079-4798-b9f3-18a2a6c7f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[1]</value>
      <webElementGuid>3f903766-00c6-4118-a37e-8cb65c9b7b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add product route operation workcenter']/parent::*</value>
      <webElementGuid>8e5a9582-89b6-4ce5-bc1b-caceb071f646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>788f2997-e025-41bc-b30c-4c7e7f242b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Add product route operation workcenter' or . = 'Add product route operation workcenter')]</value>
      <webElementGuid>78a3dcbd-c893-4d3a-a90a-095bed5e3373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
