<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>autocomplete_Product_Selected</name>
   <tag></tag>
   <elementGuidId>18afa8fd-c62c-4787-8fdb-03149dd78e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='bom-lookup-productid-12']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[starts-with(@id, 'bom-lookup-productid-') and (text() = '100864' or . = '100864')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bom-lookup-productid-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>570ab449-5e25-48c9-8c7f-30ad60615f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>template disp-block ng-star-inserted</value>
      <webElementGuid>ca9b4cd8-6d0e-42c6-9862-9178eea91d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bom-lookup-productid-</value>
      <webElementGuid>dbee0b6f-b01b-4fb3-a6ba-114a390dd6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100864</value>
      <webElementGuid>69eeec68-34d0-4998-8523-88ed0b9a7b55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='bom-lookup-productid-12']</value>
      <webElementGuid>802fe35f-29c1-49c9-9180-0f9e329aecf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='5d14b0c8-25a7-4d4d-96c9-9c8789656920-dabf5833-9bb1-438c-b611-b057168cc982']/span</value>
      <webElementGuid>e0265b75-fd5d-42e9-b0e2-30abf9ce8e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[3]/following::span[12]</value>
      <webElementGuid>fedd5ea7-5efc-4f4c-b258-dc507038fa8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[13]</value>
      <webElementGuid>47a554ec-05f8-4b9c-bf8d-fcb64a5243a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ImportProduct000100'])[1]/preceding::span[18]</value>
      <webElementGuid>665181df-2c9f-46fa-81f7-e8417074ded1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new product 100869'])[1]/preceding::span[19]</value>
      <webElementGuid>8096c1f9-a078-4129-a815-40284a30438d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100864']/parent::*</value>
      <webElementGuid>2f09bffe-90cc-4196-b309-adb5866d70f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[13]/span</value>
      <webElementGuid>b188c027-adcd-4b8f-8415-1bba02eee804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'bom-lookup-productid-12' and (text() = '100864' or . = '100864')]</value>
      <webElementGuid>981ed154-d828-4b4d-a556-a409e51ebc02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
