<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>autocomplete_Product</name>
   <tag></tag>
   <elementGuidId>2aba9e77-8bc4-4821-9f97-fe6ffb215d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='k-bom-lookup-productid']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'k-bom-lookup-productid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#k-bom-lookup-productid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9fc03f8-b9f1-4941-9ad8-2de2403e3832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc7ffd84-2eb5-4afc-88ea-6db64eab6857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>83796b75-3edd-4cf2-95d6-231144f17907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f6f51c1f-6ee7-4004-a658-13b29ff795a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input-inner</value>
      <webElementGuid>2ccebf3b-5dce-4578-a5ca-cf022c47131c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>k-bom-lookup-productid</value>
      <webElementGuid>dc1dc0f0-cf2b-430d-8469-0828c332e484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a3b7f225-b420-40d9-9813-ff6df6b9c31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>8d008333-6836-4455-a6ce-a4934a24797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5502e32a-e4fc-4f86-b176-24794b8d9e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>344310ef-3404-4b94-88aa-91ea368330a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e42b0ee8-d559-4d09-b4f1-ca67673e2f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3beb6b4-b4dd-4703-82dd-7718b9872f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>cf33f693-bed3-4092-b6ae-fd41b11dda31</value>
      <webElementGuid>feaabca5-f4ea-4070-a308-fa1149c854c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NO DATA FOUND</value>
      <webElementGuid>85de02cc-b885-4473-89e6-ef8cb40ca526</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='k-bom-lookup-productid']</value>
      <webElementGuid>0f22e880-fc11-4a40-9cc4-16a81f0ff62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductId']/div[2]/dropdown/div/kendo-combobox/kendo-searchbar/input</value>
      <webElementGuid>bff11344-80a8-41a3-9a28-ee537ea906c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//kendo-searchbar/input</value>
      <webElementGuid>67ac9b5c-389e-4db8-aef4-378c75e46dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'k-bom-lookup-productid']</value>
      <webElementGuid>9b791eb9-777c-4c4d-b1c5-d99a02297a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
