<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>richmultiselect_Product_Selected</name>
   <tag></tag>
   <elementGuidId>d0da8391-8f70-4fa9-b2bf-964b824e6c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_ProductId']/div[2]/dropdown/div/custom-dropdown/div/div/div/div/div/div/div[2]/div[2]/div/label[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tn_ProductId&quot;)//following::dropdown[@class=&quot;ng-star-inserted&quot;]//child::custom-dropdown[@class=&quot;ng-star-inserted&quot;]//child::label[count(. | //*[(text() = '100797' or . = '100797')]) = count(//*[(text() = '100797' or . = '100797')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9902e538-0a48-4d71-999c-67cc91137fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>info</value>
      <webElementGuid>78de6ca8-5a1f-4471-a560-420eca22c827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100797</value>
      <webElementGuid>646250ba-4972-4cf5-b4a3-cb066948704f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tn_ProductId&quot;)//following::dropdown[@class=&quot;ng-star-inserted&quot;]//child::custom-dropdown[@class=&quot;ng-star-inserted&quot;]//child::label</value>
      <webElementGuid>3ae2a061-198b-4be8-b7c6-650cd172593a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductId']/div[2]/dropdown/div/custom-dropdown/div/div/div/div/div/div/div[2]/div[2]/div/label[2]</value>
      <webElementGuid>a0ede4dc-d88c-40d7-9fa7-e9198b60ca8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code:'])[1]/following::label[1]</value>
      <webElementGuid>950df34b-4ff8-40fb-b4f4-9647695195b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[1]/following::label[2]</value>
      <webElementGuid>c7066400-b913-4b25-bbb2-c3a6dda40a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Item name:'])[1]/preceding::label[1]</value>
      <webElementGuid>f56dface-b59e-47bd-88c8-6ed7db5ec396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created on:'])[1]/preceding::label[3]</value>
      <webElementGuid>9d8abc4e-b13c-47c8-ab40-16b24c26fc20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='100797']/parent::*</value>
      <webElementGuid>4ba30c61-8875-45b5-bed2-7d9a6be4e5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>023b2897-3d77-43d7-ae20-b3645c7dc5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '100797' or . = '100797')]</value>
      <webElementGuid>43c50428-1a20-4de3-a3cb-936924920d0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
