<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>richmultiselect_Product</name>
   <tag></tag>
   <elementGuidId>f87558eb-0f79-4562-bbfb-db0aa01ae7d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-dropdown-bom-lookup-productid']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'custom-dropdown-bom-lookup-productid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#custom-dropdown-bom-lookup-productid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f04fb40-5004-4092-9aee-8d692e3235e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>148f60f8-6e06-4ed8-8fd6-19aefde3d484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7eff3c1-0b94-4436-8f78-2f633075b3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input form-control drpdwn-padding</value>
      <webElementGuid>9a1cabbe-aa96-4132-8d76-a83d14f5dfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-dropdown-bom-lookup-productid</value>
      <webElementGuid>ae77a019-8a6b-4f02-8675-646329be7b38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-dropdown-bom-lookup-productid']</value>
      <webElementGuid>b522f491-14f5-47d2-aaf3-0f1643f7afbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductId']/div[2]/dropdown/div/custom-dropdown/div/div/div/div/input</value>
      <webElementGuid>bcb8a429-ed6f-492c-afac-92c9a306eaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>a05894f0-9841-40bc-b782-c51e5468fbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'custom-dropdown-bom-lookup-productid']</value>
      <webElementGuid>227c65cc-5636-4e54-9524-7464cf8d6cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
