<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_productgroup</name>
   <tag></tag>
   <elementGuidId>6f541c02-c383-4cb9-91bb-e04baded2c6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product-lookup-productgroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-lookup-productgroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>339734b7-274e-403e-a5b5-fe438acbc37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>0f8754e0-2623-40f2-880f-b0923922c145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>1bd1a101-2b99-4d9b-b5c5-1397958c57db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-lookup-productgroup</value>
      <webElementGuid>4130e68b-2463-4e13-b579-ff3d600572cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-lookup-productgroup&quot;)</value>
      <webElementGuid>fe54736e-cdcc-4b32-8185-5273b40479c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='product-lookup-productgroup']</value>
      <webElementGuid>e6444e00-0a18-4f74-9d0e-dd0c87ec1292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-c25e5aeb-d9c8-4f39-b42e-66fb210b304c']/span</value>
      <webElementGuid>d34f99f7-dc24-483a-8009-f22146da66d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product type'])[1]/following::span[2]</value>
      <webElementGuid>6de5344f-4035-405b-b7a2-dcf27ed85e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/following::span[5]</value>
      <webElementGuid>1d5a5ba4-6b5d-4a20-9c83-46cef862e863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::span[3]</value>
      <webElementGuid>fa7cc3d9-53cb-4598-8d75-c86d6b5f3294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-tree-node[3]/div/div/div/div[2]/dropdown/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>2de1a961-1da2-40ef-af60-945a71edbe48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'product-lookup-productgroup']</value>
      <webElementGuid>a147f578-2136-4ad7-91a5-918a2c25bc5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
