<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_ExpandDetails_1</name>
   <tag></tag>
   <elementGuidId>96e027e3-d175-4023-8a9d-716dd70e3027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[2]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tn_ProductRouteOperation&quot;)//following::tr[@class=&quot;k-master-row ng-star-inserted&quot;]//child::a[count(. | //*[@title = 'Expand Details']) = count(//*[@title = 'Expand Details'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.k-icon.k-i-plus.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86842788-58a7-4af8-ae50-a4cb282f47c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>35345a71-7025-40b0-b2d4-d452697f4b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>727530f9-8ae7-442f-8872-1bf20f043c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-i-plus ng-star-inserted</value>
      <webElementGuid>b6de25fe-069a-471f-80ef-9d2a0384f1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expand Details</value>
      <webElementGuid>eb1ea3d1-3c09-4510-ac86-4e6d04ee692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Expand Details</value>
      <webElementGuid>01fa8c6d-949a-4b44-aa59-522f7c210d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tn_ProductRouteOperation&quot;)//following::tr[@class=&quot;k-master-row ng-star-inserted&quot;]//child::a</value>
      <webElementGuid>219ab790-41f0-4694-8e39-7fc6c74441cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[2]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr/td/a</value>
      <webElementGuid>a59b0b9b-7aa6-4823-b5aa-00b708238f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>5785e0f1-178f-477b-af67-bf4adff63d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>ba62113b-f57e-463a-b1b8-69d091edbe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Expand Details']</value>
      <webElementGuid>3e528ef1-6da9-47f5-90e4-52b1abed34f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
