<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_ProductRouteOperation</name>
   <tag></tag>
   <elementGuidId>65c53d96-becf-4781-a556-2ec381bf4715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productroute-tab-02']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'productroute-tab-02' and (text() = ' Operation ' or . = ' Operation ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productroute-tab-02</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ede0b9f-e1ff-4861-9bd2-1ad33a05cd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block ng-star-inserted</value>
      <webElementGuid>725728ed-c0c6-4cae-9c2c-401fe563efb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productroute-tab-02</value>
      <webElementGuid>d7524cc3-02ca-4bb0-a754-3daa3bf4e51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Operation </value>
      <webElementGuid>0b749468-a40b-467e-8db3-a2c3baef1e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productroute-tab-02']</value>
      <webElementGuid>bcf70fd4-690d-4123-b31e-908423f17faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-0-1']/div/span</value>
      <webElementGuid>d52bb0fd-e7a9-473a-88d5-8492376db3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document'])[1]/following::span[1]</value>
      <webElementGuid>f5f79623-a380-480c-afd6-51c41140293f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version no.'])[1]/following::span[2]</value>
      <webElementGuid>abdcc910-4bb2-41c2-91d0-2e9d02624582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Production'])[1]/preceding::span[1]</value>
      <webElementGuid>11d366b4-150f-44b5-9fdd-037c113f998c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transition history'])[1]/preceding::span[2]</value>
      <webElementGuid>81e20a39-0b7e-4113-a175-ce1f24faa964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Operation']/parent::*</value>
      <webElementGuid>ddaeec0a-9643-4264-85a7-6ae4413d1e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/span</value>
      <webElementGuid>7a97e5eb-fee0-4248-806f-b0f00c8118bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productroute-tab-02' and (text() = ' Operation ' or . = ' Operation ')]</value>
      <webElementGuid>398f6b91-eb37-499d-91ea-54e292e6592e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
