<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Assembly</name>
   <tag></tag>
   <elementGuidId>f863cbad-fa47-4764-bf89-cda5c73dbe1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[2]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[2]/td[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;tn_ProductRouteOperation&quot;)//following::table[@class=&quot;k-grid-table&quot;]//child::tbody//child::tr[2]//child::td[count(. | //*[(text() = 'CNC' or . = 'CNC')]) = count(//*[(text() = 'CNC' or . = 'CNC')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.k-touch-action-auto.ng-star-inserted.k-state-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e036d371-9a8d-44e6-bb53-96e8bf67de8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>33a4e3a9-77ce-46f3-bf7c-ef3577b02769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-touch-action-auto ng-star-inserted k-state-focused</value>
      <webElementGuid>6162e89a-08d0-4677-b553-311a5bad00e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kendo-grid-column-index</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8fe10abc-5ad0-4361-b98c-821ca9690f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4b9d516-2bf4-41af-9772-5638db7883be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b352b534-192c-487f-9b8b-d7d9d0ef47ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c7ada56c-3541-45c7-b66c-87c199e756ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CNC</value>
      <webElementGuid>9d88e722-5b5c-48b0-84dd-8fcf79e9fceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tn_ProductRouteOperation&quot;)//following::table[@class=&quot;k-grid-table&quot;]//child::tbody//child::tr[2]//child::td</value>
      <webElementGuid>3ad78c58-d069-44c0-8fba-a904daa76d98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[2]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[2]/td[5]</value>
      <webElementGuid>daf60729-921d-4d69-9e2d-0bb6f1f4c592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRO22000062'])[2]/following::td[2]</value>
      <webElementGuid>c597ecc9-ecd2-4177-bc83-d64397ca03ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRO22000062'])[1]/following::td[3]</value>
      <webElementGuid>3e6a6967-25ed-4a23-980c-3ad632fa7f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/preceding::td[3]</value>
      <webElementGuid>0ae774f1-eae5-406a-85db-215371933bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]</value>
      <webElementGuid>dca4cdc9-8416-49be-8ad9-0b30cb69dda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CNC' or . = 'CNC')]</value>
      <webElementGuid>cf8b7a94-b6eb-4a69-8da0-5d60d59fa838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
