<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_CompetenceList_MayBeNotNeeded</name>
   <tag></tag>
   <elementGuidId>93145855-7f3a-4132-9918-3524d07ce9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_Competence']/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div[2]/ul[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>37e87737-2327-459d-99b1-86a24db1f60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item2</value>
      <webElementGuid>c84583ea-cf58-4742-9bde-2866a9187cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01AdvanceCOMNEW46123ExpertIntermidateNovicetest 1.0TEST(3.0)test_user_data_01test_user_data_02</value>
      <webElementGuid>f796b37b-2e77-4ab4-8dc0-2921bc3c073c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tn_Competence&quot;)/div[2]/multiselect-dropdown[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;floating-wrapper ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/ng-multiselect-dropdown[@class=&quot;custom-multi-select ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;multiselect-dropdown&quot;]/div[@class=&quot;dropdown-list&quot;]/ul[@class=&quot;item2&quot;]</value>
      <webElementGuid>12d05d3c-3ddb-4144-ab0c-f1b7e1cfee47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_Competence']/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div[2]/ul[2]</value>
      <webElementGuid>87cfaeed-1550-4e58-a11c-f6f4e789bd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/following::ul[1]</value>
      <webElementGuid>62534a1c-6061-4e15-8b5c-699a1573b91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[2]/following::ul[2]</value>
      <webElementGuid>e3fc02b7-6bf8-4b40-a3d9-076164933afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-tree-node[4]/div/div/div/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div[2]/ul[2]</value>
      <webElementGuid>2e2d9780-e479-4b7e-8189-af26b189b0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = '01AdvanceCOMNEW46123ExpertIntermidateNovicetest 1.0TEST(3.0)test_user_data_01test_user_data_02' or . = '01AdvanceCOMNEW46123ExpertIntermidateNovicetest 1.0TEST(3.0)test_user_data_01test_user_data_02')]</value>
      <webElementGuid>c99ebd21-93bc-414c-9e96-5fef2e782bbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
