<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Competence</name>
   <tag></tag>
   <elementGuidId>add0ff21-705a-4dd0-b363-470d5d9dbba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_Competence']/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='tn_Competence']//following::multiselect-dropdown</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b49ea5c-f88e-4597-9693-f89f177f6f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-btn</value>
      <webElementGuid>544e6d1c-1738-4fa3-b1c1-5aa16c7625a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c89e6ea5-8eb3-46eb-bef2-fd3384d125ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>36a6e835-8af3-465e-81a2-359dcbe8de8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='tn_Competence']//following::multiselect-dropdown</value>
      <webElementGuid>31b7e298-f931-4699-9286-df44fad15a52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_Competence']/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div/span</value>
      <webElementGuid>4899499c-6352-4726-9d19-d8154e4c35ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::span[1]</value>
      <webElementGuid>02457a28-ce01-4f32-9295-c56780750254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[2]/preceding::span[4]</value>
      <webElementGuid>5ae8ec2f-a934-4039-8af8-1a5251a9418a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-tree-node[4]/div/div/div/div[2]/multiselect-dropdown/div/div/ng-multiselect-dropdown/div/div/span</value>
      <webElementGuid>262a3a5a-5a74-493c-a8b3-4f7f265b9bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>afc06793-a87d-4694-9a82-f066e73920df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
