<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_StopDrillDown</name>
   <tag></tag>
   <elementGuidId>3f25a19d-f34a-41d4-869a-833ae8e6b4d8</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tn_StopDrillDown']/div[2]/checkbox/div/div/div/label/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>.//*[@id='tn_StopDrillDown']//following::span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.control__indicator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afc300da-dcaf-4be4-b666-21429116de9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control__indicator</value>
      <webElementGuid>bab04b34-e439-484b-8255-3acbad2ce343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>.//*[@id='tn_StopDrillDown']//following::span</value>
      <webElementGuid>acf97041-161c-4761-96bc-787259058363</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_StopDrillDown']/div[2]/checkbox/div/div/div/label/span</value>
      <webElementGuid>b9fb2e2e-7dd4-4b8f-9ff7-9376ab5204b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//checkbox/div/div/div/label/span</value>
      <webElementGuid>2cbd308b-46b9-4ec3-8194-9953de04fa7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
