<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product_productgroup</name>
   <tag></tag>
   <elementGuidId>bd826cb8-ca1b-486c-a867-8e4cc1c6c569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='product-lookup-productgroup']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'product-lookup-productgroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-lookup-productgroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5caa52ea-09ea-4869-9f05-18b71d7aba2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>6c1c74c9-ca29-44e4-81fb-1a2a713da6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d1ee1298-7c48-44c4-b730-276a9b49eccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-lookup-productgroup</value>
      <webElementGuid>9f395991-2da9-49f4-ba73-dde675590b7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='product-lookup-productgroup']</value>
      <webElementGuid>8ad9c4ab-322d-4d21-8b55-512a1b475129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='k-a74f5a47-9bfa-4d0d-b4f2-b3cf28eca15f']/span</value>
      <webElementGuid>5b16a91f-4d35-464b-a7ad-95d87d383408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product type'])[1]/following::span[2]</value>
      <webElementGuid>1d46281f-36f6-4169-aee5-d2b2cf604a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/following::span[5]</value>
      <webElementGuid>61d9eb79-6461-43c3-9456-8a4a48b3c4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::span[3]</value>
      <webElementGuid>7e2d8f0d-71da-49c2-9917-06fbf6b929c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-tree-node[3]/div/div/div/div[2]/dropdown/div/kendo-dropdownlist/span/span</value>
      <webElementGuid>efc767fb-b700-418d-84a8-bf94001d6d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'product-lookup-productgroup']</value>
      <webElementGuid>8b3d8ee2-e718-4098-8f47-2c0bcc582616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
