<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_CanBeManufactured</name>
   <tag></tag>
   <elementGuidId>8403e992-3efd-478e-bd65-835558da3e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='product-bool-canbemanufactured']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-bool-canbemanufactured > label.mat-slide-toggle-label > div.mat-slide-toggle-bar.mat-slide-toggle-bar-no-side-margin > div.mat-slide-toggle-thumb-container > div.mat-slide-toggle-thumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f6b9e5d-ad46-44a0-8741-7911f64fd579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-slide-toggle-thumb</value>
      <webElementGuid>5d219640-225f-4c16-861c-1929c045992e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='product-bool-canbemanufactured']</value>
      <webElementGuid>a9a36a98-6769-417f-ae26-bbe19daff945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-slide-toggle[@id='product-bool-canbemanufactured']/label/div/div/div</value>
      <webElementGuid>5d493515-e474-433e-877e-3b56e32bc773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//my-tree-node[5]/div/div/div/div[2]/checkbox/div/div/toggle/div/div/div/label/mat-slide-toggle/label/div/div/div</value>
      <webElementGuid>700ca000-6644-4f5f-a37c-e2d0b7853022</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
