<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>child_button_Add</name>
   <tag></tag>
   <elementGuidId>bd27cf27-4786-43fa-9f4b-f3b04f5295cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productrouteoperationworkcenter-operation-add-en20030-st01</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @id = 'productrouteoperationworkcenter-operation-add-en20030-st01' and (text() = ' Add ' or . = ' Add ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='productrouteoperationworkcenter-operation-add-en20030-st01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb3093f9-9635-4e80-813c-f0ecb1764332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>82a41060-23e7-4167-9b79-1595b7e72a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>4ed8f5d4-6915-4db4-ace8-79e503847667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productrouteoperationworkcenter-operation-add-en20030-st01</value>
      <webElementGuid>e16fe7d3-73c8-4e6b-b618-d4e0e8a096e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add </value>
      <webElementGuid>e338f538-35f8-4f32-83df-9f08e7aed85e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='productrouteoperationworkcenter-operation-add-en20030-st01']</value>
      <webElementGuid>df4ea713-ed4b-4cd4-a17c-19135ea2eb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[3]/app-general-ui-list/div/detail-entity-grid/div/div[2]/kendo-grid/div/kendo-grid-list/div/div/table/tbody/tr[2]/td[2]/div[4]/div/custom/section/div/div/div[2]/utility-top-bar/h3/buttons/a</value>
      <webElementGuid>c2d8a1fc-f308-416c-98dc-b92a7653d3c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Add')])[3]</value>
      <webElementGuid>578fe472-b654-4507-90c8-475d97af6a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product route operation workcenters'])[1]/following::a[1]</value>
      <webElementGuid>03aeb776-e2d0-41aa-a852-0c35209c51a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Image:'])[3]/following::a[1]</value>
      <webElementGuid>903f57ba-6e68-4d71-a9f3-9b12049e27f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workcenter positon'])[1]/preceding::a[1]</value>
      <webElementGuid>4f157895-0b1c-47b2-b703-87584893c9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workcenter'])[2]/preceding::a[2]</value>
      <webElementGuid>69a17063-3aa7-4a48-a5ca-659d979aad6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>d909e432-3789-41dc-af95-8995bbe36706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/custom/section/div/div/div[2]/utility-top-bar/h3/buttons/a</value>
      <webElementGuid>88a92be5-8e89-41cc-aeed-a132d76ec5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'productrouteoperationworkcenter-operation-add-en20030-st01' and (text() = ' Add ' or . = ' Add ')]</value>
      <webElementGuid>99d52240-7da8-4d23-8c59-54de8d9e9cd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
