<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>parent_button_Add</name>
   <tag></tag>
   <elementGuidId>a35ca2cf-7234-47c3-99c4-a39832eb9781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productrouteoperation-operation-add-en20029-st01</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and @id = 'productrouteoperation-operation-add-en20029-st01' and (text() = ' Add ' or . = ' Add ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='productrouteoperation-operation-add-en20029-st01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13b0721a-9086-4aff-8a9a-9f670f64a575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>eeef7beb-9f2e-4bbc-a530-85a12f130e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>b44931a9-8f89-4aeb-8e23-b421d2eedcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productrouteoperation-operation-add-en20029-st01</value>
      <webElementGuid>daaec998-cc67-4d0d-8677-205a16dfd910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add </value>
      <webElementGuid>fe8aaca1-4d25-4fed-b9d1-63369dd92916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='productrouteoperation-operation-add-en20029-st01']</value>
      <webElementGuid>d0cb5fd8-e0c0-449c-aa8e-f7fc5d779a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tn_ProductRouteOperation']/div[2]/div/custom/section/div/div/div[2]/utility-top-bar/h3/buttons/a</value>
      <webElementGuid>7f4f0038-94c3-4469-8f88-1db0e2f5dea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add')]</value>
      <webElementGuid>c0f0d836-02ea-4ec6-8d5f-99a34951b733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product route operations'])[1]/following::a[1]</value>
      <webElementGuid>b4b8bcda-c2b1-44c9-a5d2-6ad959acb1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transition history'])[1]/following::a[1]</value>
      <webElementGuid>8e646822-e9de-4529-9ff9-ffafd899f0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::a[1]</value>
      <webElementGuid>b682c777-e660-4ef3-8ac8-a18d1f651cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::a[2]</value>
      <webElementGuid>2cf88dfe-c736-4c03-a2c8-0fd4439a0e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add']/parent::*</value>
      <webElementGuid>1f994ecc-62ec-489d-9c7e-bcd2890b581d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>39a3a0a7-3efd-4e36-b662-620353851f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/utility-top-bar/h3/buttons/a</value>
      <webElementGuid>8caa81ae-88fe-41c2-8408-f5b26e8de78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'productrouteoperation-operation-add-en20029-st01' and (text() = ' Add ' or . = ' Add ')]</value>
      <webElementGuid>0b3c8450-e680-4955-b679-3d0961afb499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
