<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter_AddresseeName</name>
   <tag></tag>
   <elementGuidId>95f31a20-08b0-4204-bdeb-b12bb8748e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.k-textbox.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;fixedPosition&quot;)//following::kendo-grid-filter-wrapper-cell[@class=&quot;k-filtercell-wrapper&quot;]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='fixedPosition']/app-root/div/language-init/div/div/metadata-init/app-component-initializer/general-ui-display/section/div/div[2]/app-general-ui-list/div/common-grid-data/div/kendo-grid/div/div/div/table/thead/tr[2]/td[2]/kendo-grid-string-filter-cell/kendo-grid-filter-wrapper-cell/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f08e6bf1-0e8b-4f6b-8317-805125c90d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-textbox ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d9fa77f6-09a5-4b8c-920e-1431df87e199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixedPosition&quot;)//following::kendo-grid-filter-wrapper-cell[@class=&quot;k-filtercell-wrapper&quot;]/input</value>
      <webElementGuid>6199fc92-16f6-4e1b-bef5-f92f84d48d7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fixedPosition']/app-root/div/language-init/div/div/metadata-init/app-component-initializer/general-ui-display/section/div/div[2]/app-general-ui-list/div/common-grid-data/div/kendo-grid/div/div/div/table/thead/tr[2]/td[2]/kendo-grid-string-filter-cell/kendo-grid-filter-wrapper-cell/input</value>
      <webElementGuid>9342ad8f-7da3-41b9-9109-f93821f992b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a07627b4-125e-49e7-97f9-b3cd990587e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
