<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>task_ConvertPotentialCustomer</name>
   <tag></tag>
   <elementGuidId>a349c353-f5f2-4003-ac21-c3c739ed94ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;cdk-overlay-0&quot;)//following::a[count(. | //*[(text() = '[task_convertpotentialcustomer]' or . = '[task_convertpotentialcustomer]')]) = count(//*[(text() = '[task_convertpotentialcustomer]' or . = '[task_convertpotentialcustomer]')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-0']/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>379d6b2f-e0f9-41e9-a740-1cf241eeff38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item ng-star-inserted</value>
      <webElementGuid>fe29190a-6c5d-4017-b24a-81eaca4af1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[task_convertpotentialcustomer]</value>
      <webElementGuid>9d866e27-0334-4682-b3b1-2b54e389aca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-0&quot;)//following::a</value>
      <webElementGuid>b4e524a1-d88d-43eb-816d-6aec693eed0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-0']/div/div/div/a</value>
      <webElementGuid>353e70f0-05d7-47fb-95f6-89299757be67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'[task_convertpotentialcustomer]')]</value>
      <webElementGuid>3f903dc5-4930-4472-81b2-a63db464c010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::a[1]</value>
      <webElementGuid>027840e7-409f-4b72-87b3-ccf3bbfe55b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::a[1]</value>
      <webElementGuid>a42cad85-c72e-44f4-bdf5-8315c96651bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[1]</value>
      <webElementGuid>60d716b1-06d7-4b93-bafc-5e5e849192ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update status'])[1]/preceding::a[2]</value>
      <webElementGuid>7ad79768-ddb6-4ebc-8b6e-3f6fad2f299b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[task_convertpotentialcustomer]']/parent::*</value>
      <webElementGuid>57e700aa-b5a5-4659-b43d-670c2a5613a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a</value>
      <webElementGuid>71e0638c-df07-451e-abfe-90c59e9b0f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '[task_convertpotentialcustomer]' or . = '[task_convertpotentialcustomer]')]</value>
      <webElementGuid>91e5bd33-4e85-46c9-ba4e-b1e9eac55a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
