<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password</name>
   <tag></tag>
   <elementGuidId>2f864611-810b-442f-9de3-a0987dcdde7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.ng-touched.ng-dirty.ng-invalid</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@placeholder = 'Enter Password' and @type = 'password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1717ad25-cddd-40c1-a675-67a7cffb8778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>739183b7-9f5b-4258-a1e2-72b7b5261326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-touched ng-dirty ng-invalid</value>
      <webElementGuid>0c385328-2b0f-403a-b3aa-5c935d1a7b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8d4d1b42-a9b1-4b66-9c9c-d5db8363c765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Password</value>
      <webElementGuid>182bcd92-76bd-42ce-a4bc-e7d79f9eeedd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5fb99b36-6e5e-4ac8-8409-92d958109c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fixedPosition&quot;)/app-root[1]/div[1]/app-login[1]/div[@class=&quot;account-body&quot;]/div[@class=&quot;accountbg&quot;]/div[@class=&quot;row vh-100&quot;]/div[@class=&quot;col-12 align-self-center&quot;]/div[@class=&quot;auth-page&quot;]/div[@class=&quot;card auth-card shadow-lg&quot;]/div[@class=&quot;login-body&quot;]/div[@class=&quot;px-3&quot;]/form[@class=&quot;form-horizontal auth-form my-4 ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control ng-touched ng-dirty ng-invalid&quot;]</value>
      <webElementGuid>3370a220-1d0d-47d1-acca-ee8140a9e408</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='password']</value>
      <webElementGuid>bae41c8c-49be-4c42-a335-dac384e63162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='fixedPosition']/app-root/div/app-login/div/div/div/div/div/div/div/div/form/div[3]/div/input</value>
      <webElementGuid>fb47c906-d3b5-4bd4-bb24-21f352179dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>07484640-0813-434f-a89a-c63c01d4ea35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Password' and @type = 'password']</value>
      <webElementGuid>9bd69fda-2e5e-4f1d-9de4-56963c4a4ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
